version: '3.9'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3002:3002"
    working_dir: /frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3002"]
      timeout: 10s
      retries: 5
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3003:3003"
    working_dir: /backend
    command: dev
    volumes:
      - ./backend:/backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://default:onF5udGBAfx2@ep-calm-dust-a42odoyt.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3003"]
      timeout: 10s
      retries: 5
  db:
    image: postgres:13
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_PTRACE